export const coursesData = [
    {
        id: 1,
        title: "ReactJS",
        category: "FRONTEND",
        badge: "Offline",
        image: "../assets/images/course/react-course-offline.png",
        instructorAvatar: "../assets/images/avatar2.png",
        instructorName: "Jane Cooper",
        price: "4.500.000đ",
        date: "28/02/2023",
        timeline: "45 spells",
        form: "Offline"
    },
    {
        id: 2,
        title: "NodeJS",
        category: "BACKEND",
        badge: "Offline",
        image: "../assets/images/course/nodejs-course-offline.png",
        instructorAvatar: "../assets/images/avatar2.png",
        instructorName: "Jane Cooper",
        price: "4.500.000đ",
        date: "05/03/2023",
        timeline: "40 spells",
        form: "Offline"
    },
    {
        id: 3,
        title: "PHP",
        category: "BACKEND",
        badge: "Offline",
        image: "../assets/images/course/php-course.png",
        instructorAvatar: "../assets/images/avatar2.png",
        instructorName: "Jane Cooper",
        price: "4.500.000đ",
        date: "10/03/2023",
        timeline: "35 spells",
        form: "Offline"
    },
    {
        id: 4,
        title: "Flutter",
        category: "MOBILE",
        badge: "Offline",
        image: "../assets/images/course/flutter-course-offline.png",
        instructorAvatar: "../assets/images/avatar2.png",
        instructorName: "Jane Cooper",
        price: "4.500.000đ",
        date: "12/03/2023",
        timeline: "50 spells",
        form: "Offline"
    },
    {
        id: 5,
        title: "QC Tester",
        category: "QC",
        badge: "Offline",
        image: "../assets/images/course/qc-course.png",
        instructorAvatar: "../assets/images/avatar2.png",
        instructorName: "Jane Cooper",
        price: "4.500.000đ",
        date: "18/03/2023",
        timeline: "30 spells",
        form: "Offline"
    },
    {
        id: 6,
        title: "Unity 3D",
        category: "GAME",
        badge: "Offline",
        image: "../assets/images/course/unity-course-offline.png",
        instructorAvatar: "../assets/images/avatar3.png",
        instructorName: "Jane Cooper",
        price: "4.500.000đ",
        date: "22/03/2023",
        timeline: "45 spells",
        form: "Offline"
    },
    {
        id: 7,
        title: "Smart Contract",
        category: "BLOCKCHAIN",
        badge: "Offline",
        image: "../assets/images/course/blockchain-course.png",
        instructorAvatar: "../assets/images/avatar3.png",
        instructorName: "Jane Cooper",
        price: "4.500.000đ",
        date: "25/03/2023",
        timeline: "40 spells",
        form: "Offline"
    },
    {
        id: 8,
        title: "UI/UX Advanced",
        category: "DESIGN",
        badge: "Offline",
        image: "../assets/images/course/design-course.png",
        instructorAvatar: "../assets/images/avatar3.png",
        instructorName: "Jane Cooper",
        price: "4.500.000đ",
        date: "30/03/2023",
        timeline: "30 spells",
        form: "Offline"
    },
    {
        id: 1,
        title: "ReactJS",
        category: "FRONTEND",
        badge: "Offline",
        image: "../assets/images/course/react-course-offline.png",
        instructorAvatar: "../assets/images/avatar2.png",
        instructorName: "Jane Cooper",
        price: "4.500.000đ",
        date: "28/02/2023",
        timeline: "45 spells",
        form: "Offline"
    },
    {
        id: 2,
        title: "NodeJS",
        category: "BACKEND",
        badge: "Offline",
        image: "../assets/images/course/nodejs-course-offline.png",
        instructorAvatar: "../assets/images/avatar2.png",
        instructorName: "Jane Cooper",
        price: "4.500.000đ",
        date: "05/03/2023",
        timeline: "40 spells",
        form: "Offline"
    },
    {
        id: 3,
        title: "PHP",
        category: "BACKEND",
        badge: "Offline",
        image: "../assets/images/course/php-course.png",
        instructorAvatar: "../assets/images/avatar2.png",
        instructorName: "Jane Cooper",
        price: "4.500.000đ",
        date: "10/03/2023",
        timeline: "35 spells",
        form: "Offline"
    },
    {
        id: 4,
        title: "Flutter",
        category: "MOBILE",
        badge: "Offline",
        image: "../assets/images/course/flutter-course-offline.png",
        instructorAvatar: "../assets/images/avatar2.png",
        instructorName: "Jane Cooper",
        price: "4.500.000đ",
        date: "12/03/2023",
        timeline: "50 spells",
        form: "Offline"
    },
    {
        id: 5,
        title: "QC Tester",
        category: "QC",
        badge: "Offline",
        image: "../assets/images/course/qc-course.png",
        instructorAvatar: "../assets/images/avatar2.png",
        instructorName: "Jane Cooper",
        price: "4.500.000đ",
        date: "18/03/2023",
        timeline: "30 spells",
        form: "Offline"
    },
    {
        id: 6,
        title: "Unity 3D",
        category: "GAME",
        badge: "Offline",
        image: "../assets/images/course/unity-course-offline.png",
        instructorAvatar: "../assets/images/avatar3.png",
        instructorName: "Jane Cooper",
        price: "4.500.000đ",
        date: "22/03/2023",
        timeline: "45 spells",
        form: "Offline"
    },
    {
        id: 7,
        title: "Smart Contract",
        category: "BLOCKCHAIN",
        badge: "Offline",
        image: "../assets/images/course/blockchain-course.png",
        instructorAvatar: "../assets/images/avatar3.png",
        instructorName: "Jane Cooper",
        price: "4.500.000đ",
        date: "25/03/2023",
        timeline: "40 spells",
        form: "Offline"
    },
    {
        id: 8,
        title: "UI/UX Advanced",
        category: "DESIGN",
        badge: "Offline",
        image: "../assets/images/course/design-course.png",
        instructorAvatar: "../assets/images/avatar3.png",
        instructorName: "Jane Cooper",
        price: "4.500.000đ",
        date: "30/03/2023",
        timeline: "30 spells",
        form: "Offline"
    },
    {
        id: 1,
        title: "ReactJS",
        category: "FRONTEND",
        badge: "Offline",
        image: "../assets/images/course/react-course-offline.png",
        instructorAvatar: "../assets/images/avatar2.png",
        instructorName: "Jane Cooper",
        price: "4.500.000đ",
        date: "28/02/2023",
        timeline: "45 spells",
        form: "Offline"
    },
    {
        id: 2,
        title: "NodeJS",
        category: "BACKEND",
        badge: "Offline",
        image: "../assets/images/course/nodejs-course-offline.png",
        instructorAvatar: "../assets/images/avatar2.png",
        instructorName: "Jane Cooper",
        price: "4.500.000đ",
        date: "05/03/2023",
        timeline: "40 spells",
        form: "Offline"
    },
    {
        id: 3,
        title: "PHP",
        category: "BACKEND",
        badge: "Offline",
        image: "../assets/images/course/php-course.png",
        instructorAvatar: "../assets/images/avatar2.png",
        instructorName: "Jane Cooper",
        price: "4.500.000đ",
        date: "10/03/2023",
        timeline: "35 spells",
        form: "Offline"
    },
    {
        id: 4,
        title: "Flutter",
        category: "MOBILE",
        badge: "Offline",
        image: "../assets/images/course/flutter-course-offline.png",
        instructorAvatar: "../assets/images/avatar2.png",
        instructorName: "Jane Cooper",
        price: "4.500.000đ",
        date: "12/03/2023",
        timeline: "50 spells",
        form: "Offline"
    },
    {
        id: 5,
        title: "QC Tester",
        category: "QC",
        badge: "Offline",
        image: "../assets/images/course/qc-course.png",
        instructorAvatar: "../assets/images/avatar2.png",
        instructorName: "Jane Cooper",
        price: "4.500.000đ",
        date: "18/03/2023",
        timeline: "30 spells",
        form: "Offline"
    },
    {
        id: 6,
        title: "Unity 3D",
        category: "GAME",
        badge: "Offline",
        image: "../assets/images/course/unity-course-offline.png",
        instructorAvatar: "../assets/images/avatar3.png",
        instructorName: "Jane Cooper",
        price: "4.500.000đ",
        date: "22/03/2023",
        timeline: "45 spells",
        form: "Offline"
    },
    {
        id: 7,
        title: "Smart Contract",
        category: "BLOCKCHAIN",
        badge: "Offline",
        image: "../assets/images/course/blockchain-course.png",
        instructorAvatar: "../assets/images/avatar3.png",
        instructorName: "Jane Cooper",
        price: "4.500.000đ",
        date: "25/03/2023",
        timeline: "40 spells",
        form: "Offline"
    },
    {
        id: 8,
        title: "UI/UX Advanced",
        category: "DESIGN",
        badge: "Offline",
        image: "../assets/images/course/design-course.png",
        instructorAvatar: "../assets/images/avatar3.png",
        instructorName: "Jane Cooper",
        price: "4.500.000đ",
        date: "30/03/2023",
        timeline: "30 spells",
        form: "Offline"
    },
    {
        id: 1,
        title: "ReactJS",
        category: "FRONTEND",
        badge: "Offline",
        image: "../assets/images/course/react-course-offline.png",
        instructorAvatar: "../assets/images/avatar2.png",
        instructorName: "Jane Cooper",
        price: "4.500.000đ",
        date: "28/02/2023",
        timeline: "45 spells",
        form: "Offline"
    },
    {
        id: 2,
        title: "NodeJS",
        category: "BACKEND",
        badge: "Offline",
        image: "../assets/images/course/nodejs-course-offline.png",
        instructorAvatar: "../assets/images/avatar2.png",
        instructorName: "Jane Cooper",
        price: "4.500.000đ",
        date: "05/03/2023",
        timeline: "40 spells",
        form: "Offline"
    },
    {
        id: 3,
        title: "PHP",
        category: "BACKEND",
        badge: "Offline",
        image: "../assets/images/course/php-course.png",
        instructorAvatar: "../assets/images/avatar2.png",
        instructorName: "Jane Cooper",
        price: "4.500.000đ",
        date: "10/03/2023",
        timeline: "35 spells",
        form: "Offline"
    },
    {
        id: 4,
        title: "Flutter",
        category: "MOBILE",
        badge: "Offline",
        image: "../assets/images/course/flutter-course-offline.png",
        instructorAvatar: "../assets/images/avatar2.png",
        instructorName: "Jane Cooper",
        price: "4.500.000đ",
        date: "12/03/2023",
        timeline: "50 spells",
        form: "Offline"
    },
    {
        id: 5,
        title: "QC Tester",
        category: "QC",
        badge: "Offline",
        image: "../assets/images/course/qc-course.png",
        instructorAvatar: "../assets/images/avatar2.png",
        instructorName: "Jane Cooper",
        price: "4.500.000đ",
        date: "18/03/2023",
        timeline: "30 spells",
        form: "Offline"
    },
    {
        id: 6,
        title: "Unity 3D",
        category: "GAME",
        badge: "Offline",
        image: "../assets/images/course/unity-course-offline.png",
        instructorAvatar: "../assets/images/avatar3.png",
        instructorName: "Jane Cooper",
        price: "4.500.000đ",
        date: "22/03/2023",
        timeline: "45 spells",
        form: "Offline"
    },
    {
        id: 7,
        title: "Smart Contract",
        category: "BLOCKCHAIN",
        badge: "Offline",
        image: "../assets/images/course/blockchain-course.png",
        instructorAvatar: "../assets/images/avatar3.png",
        instructorName: "Jane Cooper",
        price: "4.500.000đ",
        date: "25/03/2023",
        timeline: "40 spells",
        form: "Offline"
    },
    {
        id: 8,
        title: "UI/UX Advanced",
        category: "DESIGN",
        badge: "Offline",
        image: "../assets/images/course/design-course.png",
        instructorAvatar: "../assets/images/avatar3.png",
        instructorName: "Jane Cooper",
        price: "4.500.000đ",
        date: "30/03/2023",
        timeline: "30 spells",
        form: "Offline"
    },
    {
        id: 1,
        title: "ReactJS",
        category: "FRONTEND",
        badge: "Offline",
        image: "../assets/images/course/react-course-offline.png",
        instructorAvatar: "../assets/images/avatar2.png",
        instructorName: "Jane Cooper",
        price: "4.500.000đ",
        date: "28/02/2023",
        timeline: "45 spells",
        form: "Offline"
    },
    {
        id: 2,
        title: "NodeJS",
        category: "BACKEND",
        badge: "Offline",
        image: "../assets/images/course/nodejs-course-offline.png",
        instructorAvatar: "../assets/images/avatar2.png",
        instructorName: "Jane Cooper",
        price: "4.500.000đ",
        date: "05/03/2023",
        timeline: "40 spells",
        form: "Offline"
    },
    {
        id: 3,
        title: "PHP",
        category: "BACKEND",
        badge: "Offline",
        image: "../assets/images/course/php-course.png",
        instructorAvatar: "../assets/images/avatar2.png",
        instructorName: "Jane Cooper",
        price: "4.500.000đ",
        date: "10/03/2023",
        timeline: "35 spells",
        form: "Offline"
    },
    {
        id: 4,
        title: "Flutter",
        category: "MOBILE",
        badge: "Offline",
        image: "../assets/images/course/flutter-course-offline.png",
        instructorAvatar: "../assets/images/avatar2.png",
        instructorName: "Jane Cooper",
        price: "4.500.000đ",
        date: "12/03/2023",
        timeline: "50 spells",
        form: "Offline"
    },
    {
        id: 5,
        title: "QC Tester",
        category: "QC",
        badge: "Offline",
        image: "../assets/images/course/qc-course.png",
        instructorAvatar: "../assets/images/avatar2.png",
        instructorName: "Jane Cooper",
        price: "4.500.000đ",
        date: "18/03/2023",
        timeline: "30 spells",
        form: "Offline"
    },
    {
        id: 6,
        title: "Unity 3D",
        category: "GAME",
        badge: "Offline",
        image: "../assets/images/course/unity-course-offline.png",
        instructorAvatar: "../assets/images/avatar3.png",
        instructorName: "Jane Cooper",
        price: "4.500.000đ",
        date: "22/03/2023",
        timeline: "45 spells",
        form: "Offline"
    },
    {
        id: 7,
        title: "Smart Contract",
        category: "BLOCKCHAIN",
        badge: "Offline",
        image: "../assets/images/course/blockchain-course.png",
        instructorAvatar: "../assets/images/avatar3.png",
        instructorName: "Jane Cooper",
        price: "4.500.000đ",
        date: "25/03/2023",
        timeline: "40 spells",
        form: "Offline"
    },
    {
        id: 8,
        title: "UI/UX Advanced",
        category: "DESIGN",
        badge: "Offline",
        image: "../assets/images/course/design-course.png",
        instructorAvatar: "../assets/images/avatar3.png",
        instructorName: "Jane Cooper",
        price: "4.500.000đ",
        date: "30/03/2023",
        timeline: "30 spells",
        form: "Offline"
    },

];